services:
    backlog.command_handler.create_person:
        class: Star\BacklogVelocity\Agile\Application\Command\Project\CreatePersonHandler
        arguments:
            - '@backlog.repositories.persons'
        tags:
            - { name: 'prooph_service_bus.backlog_command_bus.route_target' }

    backlog.command_handler.create_project:
        class: Star\BacklogVelocity\Agile\Application\Command\Project\CreateProjectHandler
        arguments:
            - '@backlog.repositories.projects'
        tags:
            - { name: 'prooph_service_bus.backlog_command_bus.route_target' }

    backlog.command_handler.join_team:
        class: Star\BacklogVelocity\Agile\Application\Command\Project\JoinTeamHandler
        arguments:
            - '@backlog.repositories.teams'
            - '@backlog.repositories.persons'
        tags:
            - { name: 'prooph_service_bus.backlog_command_bus.route_target' }

    backlog.command_handler.create_sprint:
        class: Star\BacklogVelocity\Agile\Application\Command\Sprint\CreateSprintHandler
        arguments:
            - '@backlog.repositories.projects'
            - '@backlog.repositories.sprints'
            - '@backlog.repositories.teams'
            - '@backlog.naming_strategy'
        tags:
            - { name: 'prooph_service_bus.backlog_command_bus.route_target' }

    backlog.command_handler.create_team:
        class: Star\BacklogVelocity\Agile\Application\Command\Project\CreateTeamHandler
        arguments:
            - '@backlog.repositories.teams'
        tags:
            - { name: 'prooph_service_bus.backlog_command_bus.route_target' }

    backlog.command_handler.start_sprint:
        class: Star\BacklogVelocity\Agile\Application\Command\Sprint\StartSprintHandler
        arguments:
            - '@backlog.repositories.sprints'
        tags:
            - { name: 'prooph_service_bus.backlog_command_bus.route_target' }

    backlog.command_handler.close_sprint:
        class: Star\BacklogVelocity\Agile\Application\Command\Sprint\CloseSprintHandler
        arguments:
            - '@backlog.repositories.sprints'
            - '@backlog.focus_calculator'
        tags:
            - { name: 'prooph_service_bus.backlog_command_bus.route_target' }

    backlog.command_handler.commit_to_sprint:
        class: Star\BacklogVelocity\Agile\Application\Command\Sprint\CommitMemberToSprintHandler
        arguments:
            - '@backlog.repositories.sprints'
            - '@backlog.repositories.persons'
        tags:
            - { name: 'prooph_service_bus.backlog_command_bus.route_target' }
