services:
    backlog.query_handler.all_members_of_team:
        class: Star\BacklogVelocity\Agile\Application\Query\Project\AllMembersOfTeamHandler
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: 'prooph_service_bus.backlog_query_bus.route_target' }

    backlog.query_handler.team_with_identity:
        class: Star\BacklogVelocity\Agile\Application\Query\Project\TeamWithIdentityHandler
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: 'prooph_service_bus.backlog_query_bus.route_target' }

    backlog.query_handler.all_teams:
        class: Star\BacklogVelocity\Agile\Application\Query\Project\AllTeamsHandler
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: 'prooph_service_bus.backlog_query_bus.route_target' }

    backlog.query_handler.all_projects:
        class: Star\BacklogVelocity\Agile\Application\Query\Project\AllProjectsHandler
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: 'prooph_service_bus.backlog_query_bus.route_target' }

    backlog.query_handler.count_sprints_in_project:
        class: Star\BacklogVelocity\Agile\Application\Query\Sprint\CountSprintsInProjectHandler
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: 'prooph_service_bus.backlog_query_bus.route_target' }

    backlog.query_handler.most_active_sprint:
        class: Star\BacklogVelocity\Agile\Application\Query\Sprint\MostActiveSprintInProjectHandler
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: 'prooph_service_bus.backlog_query_bus.route_target' }

    backlog.query_handler.sprint_with_identity:
        class: Star\BacklogVelocity\Agile\Application\Query\Sprint\SprintWithIdentityHandler
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: 'prooph_service_bus.backlog_query_bus.route_target' }

    backlog.query_handler.sprint_commitments:
        class: Star\BacklogVelocity\Agile\Application\Query\Sprint\CommitmentsOfSprintHandler
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: 'prooph_service_bus.backlog_query_bus.route_target' }

    backlog.query_handler.all_my_teams:
        class: Star\BacklogVelocity\Agile\Application\Query\Team\AllMyTeamsHandler
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: 'prooph_service_bus.backlog_query_bus.route_target' }

    backlog.query_handler.all_sprints_of_team:
        class: Star\BacklogVelocity\Agile\Application\Query\Sprint\AllSprintsOfTeamHandler
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: 'prooph_service_bus.backlog_query_bus.route_target' }
