---

- name: Update apt
  become: yes
  apt: update_cache=yes

#- name: Install System Packages
 # become: yes
  #apt: pkg={{ item }} state=latest
  #with_items:
 #   - language-pack-en
  #  - curl
   # - wget
    #- python-software-properties
#    - git
 #   - zip
  #  - unzip
   # - openjdk-7-jre-headless
#    - libmagickcore5-extra
#    - vim
 #   - libpcre3 # to avoid undefined symbol: pcre_jit_exec'

- name: Set default environment variables
  become: yes
  lineinfile:
    dest: /etc/environment
    line: "{{ item }}"
  with_items:
    - "SYMFONY_ENV={{ symfony.environment }}"
