---

- name: symfony | Download Symfony
  get_url:
    url: https://symfony.com/installer
    dest: /home/vagrant/bin/symfony
    mode: 0770

- name: Set default environment variables
  become: yes
  lineinfile:
    dest: /etc/environment
    line: "{{ item }}"
  with_items:
    - "SYMFONY_ENV={{ symfony.environment }}"

#- name: Application | Copy config
#  copy:
#    src: /vagrant/app/config/parameters.yml.dist
#    dest: /vagrant/app/config/parameters.yml
#    force: no
