language: php

php:
#  - 5.5
#  - 5.6
  - 7.0
#  - 7.1

before_script:
    - composer install --dev
    - cp config.yml.template config.yml

script:
    - phpunit
    - bin/behat
    - bin/fixtures.sh
