language: php

php:
  - 7.0
  - 7.1

before_script:
    - composer install --dev
    - cp config.yml.template config.yml

script:
    - phpunit --coverage-clover clover
    - bin/behat
    - bin/fixtures.sh
