language: php

php:
  - 7.1

before_script:
    - composer install --dev
    - cp config.yml.template config.yml
    - touch var/backlog.sqlite

script:
    - bin/phpunit
    - bin/behat
    - bin/fixtures.sh
