#!/usr/bin/env php
<?php declare(strict_types=1);
/**
 * This file is part of the backlog-velocity.
 *
 * (c) Yannick Voyer (http://github.com/yvoyer)
 */

namespace {
    require_once 'vendor/autoload.php';

    // todo move to infra namespace, make a symlink in bin on install
    use Star\BacklogVelocity\Bundle\BacklogBundle\SymfonyPluginBridge;
    use Star\BacklogVelocity\Cli\BacklogApplication;
    use Symfony\Component\Console\Output\ConsoleOutput;

    $output = new ConsoleOutput();
    $path = __DIR__ . '/app/config/parameters.yml';
    if (false === file_exists($path)) {
        $message = <<<Message
<error>\n\n
    Config file not present, you must copy the file '$path.template'
    to a '$path' file at the root folder.
\n\n</error>
Message;
        $output->writeln($message);
        exit(1);
    }

    $env = 'dev';
    $console = new BacklogApplication();
    $kernel = new AppKernel($env, $env !== 'prod');
    $console->registerPlugin(new SymfonyPluginBridge($kernel));
    exit($console->run(null, $output));
}
