#!/usr/bin/env php
<?php
/**
 * This file is part of the backlog-velocity.
 * 
 * (c) Yannick Voyer (http://github.com/yvoyer)
 */

namespace {
    require_once 'vendor/autoload.php';

    use Star\Component\Sprint\BacklogApplication;
    use Star\Plugin\Doctrine\DoctrinePlugin;
    use Symfony\Component\Console\Output\ConsoleOutput;
    use Symfony\Component\Yaml\Yaml;

    if (false === file_exists('config.yml')) {
        throw new \RuntimeException('Config file not present, please create a config.yml');
    }
    $configuration = Yaml::parse('config.yml');

    $output = new ConsoleOutput();

    $console = new BacklogApplication(__DIR__, 'dev', $configuration);
    $console->registerPlugin(new DoctrinePlugin($output));
    $console->run(null, $output);
}
