#!/usr/bin/env php
<?php
/**
 * This file is part of the backlog-velocity.
 *
 * (c) Yannick Voyer (http://github.com/yvoyer)
 */

namespace {
    require_once 'vendor/autoload.php';

    use Star\Component\Sprint\BacklogApplication;
    use Star\Plugin\Doctrine\DoctrinePlugin;
    use Symfony\Component\Console\Output\ConsoleOutput;
    use Symfony\Component\Yaml\Yaml;

    $output = new ConsoleOutput();
    if (false === file_exists('config.yml')) {
        $message = <<<Message
<error>\n\n
    Config file not present, you must copy the file 'config.yml.template'
    to a 'config.yml' file at the root folder.
\n\n</error>
Message;
        $output->writeln($message);
        exit(1);
    }

    $console = new BacklogApplication(__DIR__, 'dev', Yaml::parse('config.yml'));
    $console->registerPlugin(new DoctrinePlugin($output));
    $console->run(null, $output);
}
