---
- name: Add ppa for apache
  become: yes
  apt_repository:
    repo: 'ppa:ondrej/apache2'

- name: Adding vagrant to adm group
  become: yes
  user: name=vagrant groups=adm

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: apache | Install apache2 packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2

- name: apache | Install apache2 modules
  become: yes
  apache2_module: name={{ item }} state=present
  with_items:
    - rewrite
    - headers
    - proxy_http

- name: apache | Disable default vhost
  become: yes
  command: a2dissite 000-default
  args:
      removes: /etc/apache2/sites-enabled/000-default.conf

- name: apache | Change webserver user to vagrant
  become: yes
  lineinfile:
    dest: /etc/apache2/envvars
    regexp: ^export APACHE_RUN_USER=
    line: export APACHE_RUN_USER=vagrant

- name: apache | Change webserver group to vagrant
  become: yes
  lineinfile:
    dest: /etc/apache2/envvars
    regexp: ^export APACHE_RUN_GROUP=
    line: export APACHE_RUN_GROUP=vagrant

- name: apache | Configure vhost
  become: yes
  template:
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/app.conf

- name: apache | Enable vhost
  become: yes
  command: a2ensite app
  args:
      creates: /etc/apache2/sites-enabled/app.conf
  notify: Restart web server
