imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

# @see: http://symfony.com/doc/current/frontend/assetic/asset_management.html
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enabled: true, enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
#        form:
 #           resources:
  #              - ':form'
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - 'bootstrap_3_horizontal_layout.html.twig'
        - 'form/backlog_bootstrap_inline.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_sqlite
        path: '%database_path%'
#        driver: pdo_mysql
#        host: '%database_host%'
#        port: '%database_port%'
#        dbname: '%database_name%'
#        user: '%database_user%'
#        password: '%database_password%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            backlog:
                type: xml
                prefix: Star\Component\Sprint\Domain\Model
                dir: "%kernel.root_dir%/../src/Application/BacklogBundle/Resources/config/mappings"
                is_bundle: false

# Swiftmailer Configuration
#swiftmailer:
#    transport: '%mailer_transport%'
#    host: '%mailer_host%'
#    username: '%mailer_user%'
#    password: '%mailer_password%'
#    spool: { type: memory }

#prooph_event_store:
#    stores:
#        test_store:
#            adapter: backlog.prooph.test_adapter
#            event_emitter: backlog.prooph.test_emitter

prooph_service_bus:
    # todo Handle the command, query, and events in Compiler pass to avoid having to define here
    command_buses:
        backlog_command_bus:
            plugins:
                - 'prooph_service_bus.handle_command_invoke_strategy'
            message_factory: 'prooph_service_bus.message_factory'
            router:
                type: 'prooph_service_bus.command_bus_router'
                routes:
                    backlog.create_project: '@backlog.handler.create_project'
                    backlog.create_sprint: '@backlog.handler.create_sprint'
                    backlog.start_sprint: '@backlog.command_handler.start_sprint'
                    backlog.commit_member_to_sprint: '@backlog.command_handler.commit_to_sprint'

    query_buses:
        backlog_query_bus:
            plugins:
                - 'prooph_service_bus.finder_invoke_strategy'
            message_factory: 'prooph_service_bus.message_factory'
            router:
                type: 'prooph_service_bus.query_bus_router'
                routes:
                    'Star\Component\Sprint\Domain\Query\Project\AllMembersOfProject': '@backlog.query_handler.all_members_of_project'
                    'Star\Component\Sprint\Domain\Query\Sprint\MostActiveSprintInProject': '@backlog.query_handler.most_active_sprint'
                    'Star\Component\Sprint\Domain\Query\Sprint\CountSprintsInProject': '@backlog.query_handler.count_sprints_in_project'
                    'Star\Component\Sprint\Domain\Query\Sprint\SprintWithIdentity': '@backlog.query_handler.sprint_with_identity'
                    'Star\Component\Sprint\Domain\Query\Sprint\CommitmentsOfSprint': '@backlog.query_handler.sprint_commitments'

#    event_buses:
 #       backlog_event_bus:
  #          plugins:
   #             - 'prooph_service_bus.on_event_invoke_strategy'
    #        message_factory: 'prooph_service_bus.message_factory'
     #       router:
      #          type: 'prooph_service_bus.event_bus_router'
       #         routes:
        #            'Star\Component\Sprint\Domain\Event\ProjectWasCreated':
         #               - '@backlog.query.project_with_name'
