services:
    backlog.commands.team.list:
        class: Star\BacklogVelocity\Application\Cli\Commands\ListTeams
        arguments:
            - '@backlog.repositories.teams'

    backlog.handler.create_project:
        class: Star\Component\Sprint\Domain\Handler\CreateProjectHandler
        arguments:
            - '@backlog.repositories.projects'
        tags:
            - { name: 'prooph_service_bus.backlog_command_bus.route_target' }

    backlog.handler.create_sprint:
        class: Star\Component\Sprint\Domain\Handler\CreateSprintHandler
        arguments:
            - '@backlog.repositories.projects'
            - '@backlog.repositories.sprints'
            - '@backlog.naming_strategy'
        tags:
            - { name: 'prooph_service_bus.backlog_command_bus.route_target' }
