services:
    backlog.controllers.dashboard:
        class: Star\Component\Sprint\Application\BacklogBundle\Controller\DashboardController
        arguments:
          - '@backlog.projections.projects'

    backlog.controllers.commitments:
        class: Star\Component\Sprint\Application\BacklogBundle\Controller\CommitmentController
        arguments:
          - '@prooph_service_bus.backlog_command_bus'
          - '@backlog.messages'

    backlog.controllers.project:
        class: Star\Component\Sprint\Application\BacklogBundle\Controller\ProjectController
        arguments:
          - '@backlog.repositories.projects'
          - '@backlog.repositories.sprints'
          - '@prooph_service_bus.backlog_command_bus'
          - '@backlog.messages'

    backlog.controllers.sprint:
        class: Star\Component\Sprint\Application\BacklogBundle\Controller\SprintController
        arguments:
          - '@prooph_service_bus.backlog_command_bus'
          - '@prooph_service_bus.backlog_query_bus'
          - '@backlog.messages'

    backlog.controllers.team:
        class: Star\Component\Sprint\Application\BacklogBundle\Controller\TeamController
        arguments:
          - '@prooph_service_bus.backlog_command_bus'
          - '@prooph_service_bus.backlog_query_bus'
          - '@backlog.messages'
