services:
    backlog.command_handler.create_project:
        class: Star\Component\Sprint\Domain\Handler\CreateProjectHandler
        arguments:
            - '@backlog.repositories.projects'
        tags:
            - { name: 'prooph_service_bus.backlog_command_bus.route_target' }

    backlog.command_handler.create_sprint:
        class: Star\Component\Sprint\Domain\Handler\CreateSprintHandler
        arguments:
            - '@backlog.repositories.projects'
            - '@backlog.repositories.sprints'
            - '@backlog.naming_strategy'
        tags:
            - { name: 'prooph_service_bus.backlog_command_bus.route_target' }

    backlog.command_handler.start_sprint:
        class: Star\Component\Sprint\Domain\Handler\Sprint\StartSprintHandler
        arguments:
            - '@backlog.repositories.sprints'
        tags:
            - { name: 'prooph_service_bus.backlog_command_bus.route_target' }

    backlog.command_handler.commit_to_sprint:
        class: Star\Component\Sprint\Domain\Handler\Sprint\CommitMemberToSprintHandler
        arguments:
            - '@backlog.repositories.sprints'
        tags:
            - { name: 'prooph_service_bus.backlog_command_bus.route_target' }
