services:
    backlog.query_handler.count_sprints_in_project:
        class: Star\Component\Sprint\Domain\Query\CountSprintsInProjectHandler
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: 'prooph_service_bus.backlog_query_bus.route_target' }
