services:
    backlog.form.create_project:
      class: Star\Component\Sprint\Application\BacklogBundle\Form\CreateProjectForm
      arguments:
        - '@backlog.repositories.projects'
      tags:
        - { name: form.type }

    backlog.form.commit_to_sprint:
      class: Star\Component\Sprint\Application\BacklogBundle\Form\CommitToSprintType
      arguments:
        - '@router'
      tags:
        - { name: form.type }
