services:
    backlog.repositories.teams:
        class: Star\Plugin\Doctrine\Repository\DoctrineTeamRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'Star\Component\Sprint\Domain\Model\TeamModel'

    backlog.repositories.projects:
        class: Star\Plugin\Doctrine\Repository\DoctrineProjectRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'Star\Component\Sprint\Domain\Model\ProjectAggregate'

    backlog.repositories.sprints:
        class: Star\Plugin\Doctrine\Repository\DoctrineSprintRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'Star\Component\Sprint\Domain\Model\SprintModel'
