services:
    backlog.repositories.teams:
        class: Star\Plugin\Doctrine\Repository\DoctrineTeamRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'Star\Component\Sprint\Domain\Model\TeamModel'
